Add footer using Nuxt UI and Tailwind
bcgov/business-transparency-registry pull request #14
Opened 2023-10-07 00:56 UTC by patrickpeinanw

The Tooltip is working but the pop-up text box still have the default style of Nuxt UI.

2023-10-09 20:30 UTC, hfekete requested changes

2023-10-09 20:30 UTC, hfekete commented on btr-web/btr-layouts/components/footer/BcrosFooter.vue
> +import pkg from '../../package.json'
Could you move this to parent, and get it here as a prop, like we chatted ?

2023-10-09 20:30 UTC, hfekete commented on btr-web/btr-layouts/components/footer/BcrosFooter.vue
> +.tooltip-icon {
Colors are ok for now, but should be put in a common place. I have created a ticket for this

[extract colors ticket](https://app.zenhub.com/workspaces/registries-benowner-644043015b6fa1002c69a9f4/issues/gh/bcgov/entity/18126)

2023-10-09 20:30 UTC, hfekete commented on btr-web/btr-layouts/components/footer/BcrosFooter.vue
> +@media (min-width: 960px) {
Did it end up having effect ? I remember some margins changed, when you were showcasing it, but I do not remember if it had any visible effect for human thats reading it.

2023-10-10 16:11 UTC, kialj876 requested changes
Hey patrick I've got few comments for ya. Also can you please add a basic unit test for this component

2023-10-11 22:22 UTC, hfekete commented on btr-web/btr-layouts/components/footer/BcrosFooter.vue
> +@media (min-width: 960px) {
Lets remove it for now, and see if we need to add it down the line. We should probably add the separators for all sizes.
As if I remember we do not work towards supporting different screen sizes.

You can do something like border-l-2 which is border left 2px, except on the last element :)

2023-10-12 15:31 UTC, kialj876 commented on btr-web/btr-layouts/components/footer/BcrosFooter.vue
> +const { appVersion } = defineProps({
For this case you can simply do this:
`defineProps<{appVersion: string}>()`
It's a required value so you don't need a default and you can access props directly in the dom

2023-10-12 18:18 UTC, kialj876 requested changes

2023-10-12 18:18 UTC, kialj876 commented on btr-api/migrations/versions/2049364ea0a6_.py
> +"""empty message
Hey patrick can you fix your branch so that it doesn't include hrvoje's stuff as a new commit ?

2023-10-12 18:19 UTC, kialj876 commented on btr-api/migrations/versions/2049364ea0a6_.py
> +"""empty message
if you need help rebasing let me know

2023-10-13 16:50 UTC, hfekete approved these changes

2023-10-13 16:55 UTC, merged