18887 - Create Schema
bcgov/business-transparency-registry pull request #86
Opened 2023-12-19 16:49 UTC by hfekete

*Issue:18887 *https://github.com/bcgov/entity/issues/18887 

*Description of changes:*
- adding JSON schema to verify API requests
- some updates to the backend
- started adding tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

2023-12-20 02:58 UTC, thorwolpert requested changes
the schema naming should follow our existing standards, which are also inline with bods

2023-12-20 02:58 UTC, thorwolpert commented on btr-api/src/btr_api/schemas/SignificantIndividualsFiling.json
> +      "enum": ["add", "edit", "remove"],
i don't think we should have actions like this.
in other filings, and it looks like bods is the same, that a submission is for the entire current state.
as such, if a person has an identifier they get updated, if they don't have one they're created and if they are in the longitudinal record but not in the filing they are removed.

2023-12-20 02:58 UTC, thorwolpert commented on btr-api/src/btr_api/schemas/SignificantIndividualsFiling.json
> +    "CitizenshipTypeE": {
In all our schemas, and in openownership the elements are all camelCase.
Please follow that standard

2023-12-20 02:58 UTC, thorwolpert commented on btr-api/src/btr_api/resources/json_schema.py
> +def list_all_schemas():
We would probably statically publish these, so it's not needed to add an active end-point for this.

2023-12-21 23:59 UTC, kialj876 commented
Looks good to me, but can you update it to run the tests successfully? Looks like it errs to run due to an import issue on the test_schema...

2023-12-22 21:24 UTC, kialj876 approved these changes

2023-12-22 21:28 UTC, merged